language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

before_script:
  - curl --version

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script: vendor/bin/phpunit
